Repository ros-infrastructure/superflore, pull requests merged in 2018-03, with the labels that each got.

#140 Added tests for parser.py.
  tests/test_parser.py
Labels: enhancement, in review

#142 Add tests for TempfileManager
  tests/test_TempfileManager.py
Labels: enhancement, in progress

#144 Adding coverage for exceptions.py
  tests/test_utils.py
Labels: enhancement, in progress

#145 Add CacheManager tests.
  tests/test_CacheManager.py
Labels: enhancement, in review

#147 Create a way to get the log from the docker container.
  .travis.yml
  README.md
  superflore/docker.py
  superflore/test_integration/gentoo/build_base.py
  superflore/test_integration/gentoo/main.py
  tests/test_docker.py
Labels: enhancement, in review

#148 Even more utils tests
  superflore/utils.py
  tests/test_utils.py
Labels: bug, enhancement, in review

#149 Add Melodic to list
  superflore/generators/ebuild/overlay_instance.py
  superflore/utils.py
Labels: enhancement, in review

#150 Fix lack of command text in PR's.
  superflore/utils.py
  tests/test_utils.py
Labels: bug, in review
