Repository ros-infrastructure/superflore, pull requests merged in 2019-12, with the labels that each got.

#235 Show OpenEmbedded recipe names in commit and PR messages (#225)
  superflore/generate_installers.py
  superflore/generators/bitbake/gen_packages.py
  superflore/generators/ebuild/gen_packages.py
  tests/test_generate_installers.py
Labels: enhancement, in progress

#247 repo_instance: initialize gh_upstream only when creating pull request (#246)
  README.md
  superflore/exceptions.py
  superflore/generators/bitbake/run.py
  superflore/generators/ebuild/run.py
  superflore/repo_instance.py
Labels: bug, enhancement, in review

#243 Use "ebuild"/"recipe" instead of "installer" (#226)
  superflore/generate_installers.py
  superflore/generators/bitbake/gen_packages.py
  superflore/generators/ebuild/gen_packages.py
Labels: enhancement, in progress

#261 yocto_recipe.py: bump ROS_SUPERFLORE_GENERATION_SCHEME
  superflore/generators/bitbake/yocto_recipe.py
Labels: enhancement, in review

#257 Fix #229
  superflore/generators/ebuild/run.py
Labels: bug, in review

#263 Release superflore version 0.3.1
  CHANGELOG.md
  setup.py
Labels: enhancement, in review
