Repository ros-infrastructure/superflore, pull requests merged in 2019-06, with the labels that each got.

#168 Initial OpenEmbedded Support for ROS 2
  requirements.txt
  setup.py
  stdeb.cfg
  superflore/PackageMetadata.py
  superflore/generate_installers.py
  superflore/generators/bitbake/gen_packages.py
  superflore/generators/bitbake/oe_query.py
  superflore/generators/bitbake/ros_meta.py
  superflore/generators/bitbake/run.py
  superflore/generators/bitbake/yocto_recipe.py
  superflore/utils.py
  tests/test_oe_query.py
  tests/test_utils.py
Labels: enhancement, in review

#194 Check missing dependencies before checking preserve_existing
  superflore/generate_installers.py
Labels: bug, enhancement, in review

#196 Fix ros-None in Gentoo Commit Messages
  superflore/generators/ebuild/overlay_instance.py
Labels: bug, enhancement, in review

#199 Fix CI
  .travis.yml
Labels: enhancement

#192 Add superflore version to ros-distro.inc
  superflore/generators/bitbake/yocto_recipe.py
  superflore/utils.py
  tests/test_utils.py
Labels: enhancement, in review

#201 Change Back to apt-get for CI
  .travis.yml
Labels: enhancement, in review

#198 Remove test-only components from world
  superflore/generators/bitbake/yocto_recipe.py
Labels: enhancement, in review
