Repository ros-infrastructure/superflore, pull requests merged in 2019-04, with the labels that each got.

#169 Small cleanups
  superflore/generate_installers.py
  superflore/generators/bitbake/gen_packages.py
  superflore/generators/bitbake/ros_meta.py
  superflore/generators/bitbake/run.py
  superflore/generators/bitbake/yocto_recipe.py
  superflore/generators/ebuild/gen_packages.py
  superflore/generators/ebuild/overlay_instance.py
  superflore/generators/ebuild/run.py
  superflore/repo_instance.py
  superflore/utils.py
Labels: enhancement, in review

#174 Fix small syntax issue
  superflore/generators/ebuild/gen_packages.py
Labels: bug, in review

#175 Add `--skip-keys` option
  superflore/generate_installers.py
  superflore/generators/bitbake/run.py
  superflore/generators/ebuild/run.py
  superflore/parser.py
Labels: enhancement, in review

#181 Fix assorted typos
  README.md
  tests/test_docker.py
  tests/test_utils.py
Labels: enhancement, in progress

#180 Add `--upstream-branch` option
  README.md
  superflore/generators/bitbake/ros_meta.py
  superflore/generators/bitbake/run.py
  superflore/generators/ebuild/overlay_instance.py
  superflore/generators/ebuild/run.py
  superflore/parser.py
  superflore/repo_instance.py
  tests/test_parser.py
Labels: enhancement, in review

#182 Fix args.all handling
  superflore/generators/bitbake/ros_meta.py
  superflore/generators/bitbake/run.py
  superflore/generators/ebuild/overlay_instance.py
  superflore/generators/ebuild/run.py
Labels: bug, enhancement, in review
