Repository ros-infrastructure/superflore, pull requests merged in 2019-07, with the labels that each got.

#208 Retry pushing when wrong credentials are provided or there's an error
  superflore/repo_instance.py
  superflore/utils.py
Labels: enhancement, in review

#216 Add an optional title parameter to the overlay pull_request method
  superflore/generators/bitbake/ros_meta.py
  superflore/generators/bitbake/run.py
  superflore/generators/ebuild/overlay_instance.py
  superflore/generators/ebuild/run.py
Labels: enhancement, in review

#218 Don't output missing dependencies for OpenEmbedded
  superflore/generators/bitbake/run.py
Labels: bug, enhancement, in review

#200 Change to Personal Email
  superflore/generators/ebuild/metadata_xml.py
Labels: enhancement, in review

#190 Release v0.3.0
  CHANGELOG.md
  setup.py
Labels: enhancement, in progress

#221 Update license classifier.
  setup.py
Labels: enhancement, in review

#214 Adjust PR message stating how superflore was executed
  superflore/utils.py
  tests/test_utils.py
Labels: enhancement, in progress
